### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by kenjonespizza** [joshnuss/svelte-local-storage-store#2]
Hi!  I'm attempting to use this on my Sapper project.  I'm new to Svelte, so let me know if this is a dumb mistake.

I can't seem to get this package to run without getthig the following error in my terminal:
```
[0] /www/public/sapper/osprey-sapper/site/__sapper__/dev/server/server.js:5694
[0]   const json = typeof(localStorage) != 'undefined' ?? localStorage.getItem(key);
[0]                                                     ^
[0] 
[0] SyntaxError: Unexpected token '?'
[0]     at wrapSafe (internal/modules/cjs/loader.js:1071:16)
[0]     at Module._compile (internal/modules/cjs/loader.js:1121:27)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
[0]     at Module.load (internal/modules/cjs/loader.js:1001:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:900:14)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[0]     at internal/main/run_main_module.js:18:47
[0] > Server crashed
```

My `stores.js` looks like this
```
import { writable } from 'svelte-local-storage-store'

export const theme = writable('theme','dark')
```

And then, once I drop this code in my component, is when I get the error
```
<script>
  import { theme } from '../../stores'

  ...

<div>{$theme}</div>
```

**Comment by joshnuss** [comment]
Hi @kenjonespizza 

Oh I see the issue. `??` is a new JS operator.
Svelte started allowing it only recently, see: https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3240

So the `svelte` package version should be `>= 3.24.0`. 

Can you try bumping your version and see if it fixes it?

**Comment by kenjonespizza** [comment]
Hi @joshnuss !  Thanks for learnin me about nullish coalecing & optional chaining making its way into Svelte!  I love using those in my previous setup with Babel.

Unfortunately updating Svelte did not solve this... which seems weird because that is the exact error I'm getting 🤔.  Maybe this is a Sapper thing... or server thing?

I ran a fresh Sapper install and: 

1. Bumped Svelte to `^3.24.1`
2. Installed `svelte-local-storage-store`
3. Added a store and imported in the Nav component
4. Still get the same error.

Here is that fresh install repo: https://github.com/kenjonespizza/test-svelte-local-storage-store.  In case you want to try it out, but no pressure 😅

The error again:
```
$ sapper dev
✔ server (1.3s)
✔ client (1.3s)
/Users/ken_docs/www/public/sapper/test-svelte-local-storage-store/__sapper__/dev/server/server.js:447
  const json = typeof(localStorage) != 'undefined' ?? localStorage.getItem(key);
                                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1071:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
> Server crashed
✔ service worker (19ms)
```

**Comment by joshnuss** [comment]
I reverted to using a regular conditional, and confirmed it's working with the `sveltejs/template`.
Update `svelte-local-storage-store` version to `0.1.3` and let me know if it's still an issue.

**Comment by joshnuss** [comment]
And thanks for reporting this!

**Comment by kenjonespizza** [comment]
Youre the 💣!  Thanks!
